---
workspace:
  output_dir: output
podcast:
  title: sample
  host: http://example.com
  image: https://example.com/image.jpg
publish:
  type: s3
  bucket: sample
schedules:
  # オードリー
  - day: sunday
    at: 01:00-04:00
    station: LFR
  # アトロク
  - day: weekday
    at: 18:00-19:00
    station: TBS
  - day: weekday
    at: 19:00-20:00
    station: TBS
  - day: weekday
    at: 20:00-21:00
    station: TBS