---
workspace:
  output_dir: output
podcast:
  title: sample
  host: http://example.com
  image: https://example.com/image.jpg
publish:
  type: s3
  bucket: sample
schedules:
  # オードリー
  - day: sunday
    at: 01:00-04:00
    station: LFR
