version: '2.3'
services:
  app:
    build: .
    command: bin/radikocast
    environment:
      - DST_DIR=./dst
      - CONFIG_PATH=./config.yml
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
    volumes:
      - .:/usr/src/app